CREATE TABLE EMAIL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FK BIGINT NOT NULL,
  DATA TIMESTAMP NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ROTINA VARCHAR(255) NOT NULL,
  TITULO VARCHAR(255) NOT NULL,
  CONTEUDO LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`)
)